management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
spring:
  jmx:
    enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
springdoc:
  swagger-ui:
    path: /
authtools:
  mock-authorities:
    - ROLE_Reader
    - SCOPE_read