name: Publish

on:
  push:
    branches:
      - main

concurrency:
  group: any
  cancel-in-progress: true

jobs:
  test_client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo_client
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install -g yarn && yarn
    - name: Install Playwright Browsers
      run: yarn playwright install chrome --with-deps
    - name: Run Playwright tests
      run: yarn test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  test_server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo_server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"
      - run: mvn test -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  publish_images:
    needs: 
      - test_client
      - test_server
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: pip
      - run: pip install -r requirements.txt
      - run: python scripts/publish_images.py ${{ secrets.GITHUB_TOKEN }} ${{ secrets.ANSIBLE_VAULT_KEY }}
